### ISSUE TITLE
Storing an SSHSession (or SSHChannel) for later use

### ISSUE THREAD

**Issue by grogancolin** [zebraxxl/libssh-d#3]
I'd like to be able to store an SSHSession for later use. (So I don't have to wait for the connection to be re-established).

I tried storing them in an array and reusing them to create a new channel etc, but it seems it was getting into some unknown state and failing.

I then tried storing the Channel for later use (keeping it open by not sending EOF to the channel) - however, when I go back and send another command I get more weirdness.

I'm just checking if you know of a way of doing this?

I can post code later of what I tried if you like :) 

Thanks!

**Comment by zebraxxl** [comment]
Because libssh-d is just bindings to libssh I think that it is a something gone wrong in libssh, not libssh-d.

> I can post code later of what I tried if you like :)

This will be great for research of that problem!

**Comment by grogancolin** [comment]
Sorry for taking so long on this - got distracted with other things!

I realised my mistake - I should cache the SSHSession object, rather than the Channel.

Creating and destroying a channel is pretty quick, creating the session is the slow bit!

Thanks for patience :)
